# Generated by Django 2.2.3 on 2019-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youthprofile',
            old_name='profile_ref',
            new_name='profile',
        ),
    ]
