# Generated by Django 2.2.3 on 2019-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20191002_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
