# Generated by Django 2.2.3 on 2019-10-02 10:55

import consents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseConsentPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description_fi', models.TextField()),
                ('description_sv', models.TextField()),
                ('description_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataUseConsent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=consents.models.year_ahead)),
                ('object_id', models.UUIDField()),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('consenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consents.DataUseConsentPurpose')),
            ],
        ),
    ]
